### ISSUE TITLE
Not working either

### ISSUE THREAD

**Issue by topninja** [NguyenThanh1995/vue-touch-scroll#1]
![image](https://user-images.githubusercontent.com/47001971/115338203-4b69c780-a1dd-11eb-8928-3a96e5bf8af2.png)

**Comment by tachibana-shin** [comment]
fixed on vue-touch-scroll@0.0.2-alpha11

Please run

``` bash
yarn add vue-touch-scroll@0.0.2-alpha11
```

**Comment by topninja** [comment]
Great.
